#!/bin/bash

cat > requirements.txt <<EOF
# Add python packages here
matplotlib
numpy
pandas

EOF

cat > environment.yml <<EOF

name: cenv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - pip:
    - black
    - neovim
    - nbval
    - pytest
    - pytest-cov
    - pytest-subtests
    - pep517
    - twine
    - -r requirements.txt

EOF
