#!/bin/bash
# Copyright 2020 A. A. Research
# Author: Tarek Allam Jr.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -o pipefail -e

mkdir -p \
    notebooks \
    bin \
    conf \
    docker \
    docs \
    libexec \
    notebooks/html \
    python/testsk \
    sbin \

mkdir -p src/{main,test}/{java,resources,scala}
echo 'name := ""
version := "1.0"
scalaVersion := "2.13.1"

libraryDependencies ++= Seq(
"org.scalactic" %% "scalactic" % "3.0.8",
"org.scalatest" %% "scalatest" % "3.0.8" % "test"
)
' > build.sbt

# bin README
echo 'Binaries
' > bin/README.md

# libexec README
echo '# External libs and JARs
' > libexec/README.md

# sbin README
echo '# Development scripts
' > sbin/README.md

# notebooks README
echo '# Jupyter Notebooks

Exploratory notebooks and data visualisation
' > notebooks/README.md

# notebooks/html README
echo '# Rendering of notebooks in HTML format

' > notebooks/html/README.md
