#!/bin/bash

function render(){
    # Find all jupyter notebooks and render them to HTML
    jupyter nbconvert --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=600 --to html --execute $1
    echo "Hello $1"
}
render
